CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL REFERENCES categories(id),
  price NUMERIC(10, 2) NOT NULL,
  compare_at NUMERIC(10, 2),
  rating NUMERIC(3, 2) NOT NULL,
  reviews INTEGER NOT NULL,
  stock INTEGER NOT NULL,
  badge TEXT,
  hue INTEGER NOT NULL,
  blurb TEXT NOT NULL,
  description TEXT NOT NULL,
  features JSONB NOT NULL,
  colors JSONB NOT NULL
);

-- Better Auth owns these four tables (user/session/account/verification) --
-- shape generated by `npx @better-auth/cli generate` against db/auth.js.
-- Never hand-edit rows; let Better Auth's own API manage them.
CREATE TABLE IF NOT EXISTS "user" (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  "emailVerified" BOOLEAN NOT NULL,
  image TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS session (
  id TEXT PRIMARY KEY,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  token TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS account (
  id TEXT PRIMARY KEY,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "idToken" TEXT,
  "accessTokenExpiresAt" TIMESTAMPTZ,
  "refreshTokenExpiresAt" TIMESTAMPTZ,
  scope TEXT,
  password TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS verification (
  id TEXT PRIMARY KEY,
  identifier TEXT NOT NULL,
  value TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS session_user_id_idx ON session ("userId");
CREATE INDEX IF NOT EXISTS account_user_id_idx ON account ("userId");
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON verification (identifier);

-- No FK to products: an order snapshots item name/price/hue/category at
-- purchase time, so it stays intact even if the catalog changes later.
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  placed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  details JSONB NOT NULL,
  items JSONB NOT NULL,
  totals JSONB NOT NULL
);

-- One-time migration off the pre-auth schema, where orders were scoped by an
-- anonymous `session_id` cookie instead of a real account. Those rows aren't
-- reachable by any account, so they're dropped rather than backfilled onto
-- one — a no-op once every environment has already migrated.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'orders' AND column_name = 'session_id'
  ) THEN
    DELETE FROM orders;
    ALTER TABLE orders DROP COLUMN session_id;
    ALTER TABLE orders ADD COLUMN user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS orders_user_idx ON orders (user_id, placed_at DESC);

-- Server-side cart/wishlist for signed-in users only. Guests keep using
-- localStorage (see src/store/StoreContext.jsx) — these tables are never
-- read for a request with no session.
-- No FK to products (same reasoning as orders, above): db:migrate reseeds
-- products via TRUNCATE ... CASCADE, which would otherwise wipe every
-- signed-in user's cart/wishlist on every reseed. A line whose product_id
-- no longer exists in the catalog is dropped client-side, same as today.
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL,
  color TEXT,
  qty INTEGER NOT NULL CHECK (qty > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS cart_items_user_product_color_idx
  ON cart_items (user_id, product_id, COALESCE(color, ''));

CREATE TABLE IF NOT EXISTS wishlist_items (
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL,
  PRIMARY KEY (user_id, product_id)
);
